# Generated by Django 5.1.6 on 2025-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='uploads/')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
            ],
        ),
        migrations.DeleteModel(
            name='infos',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
